[providers.node]
version = "20"

[phases.setup]
dependsOn = ["..."]

[phases.install]
dependsOn = ["setup"]
cmd = "npm ci"

[phases.build]
dependsOn = ["install"]
cmd = "npm run build"

[start]
cmd = "npm run start:prod"
